name: 3d_protein_probing_1

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - biotite
  - nvidia::cudatoolkit=11.3
  - einops
  - ipdb  # for debugging
  - ipython  # for debugging
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytorch::pytorch
  - pytorch-lightning
  - scikit-learn
  - scipy
  - tqdm
  - wandb
  - pip:
    - e3nn
    - fair-esm
    - tensorboardX
#    - torchdrug  # requires python 3.9
    - typed-argument-parser>=1.8.0
