name: 3d_protein_probing

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - biopython
  - cudatoolkit=11.3
  - ipdb  # for debugging
  - ipython  # for debugging
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytorch
  - pytorch-lightning
  - scikit-learn
  - scipy
  - tqdm
  - pip:
    - fair-esm
    - typed-argument-parser
